server:  
  port: ${PORT:8080}

spring:  
  application:
    name: Mongo DB Example
  data:
    mongodb:
      host: 172.30.146.57
      port: 27017
      username: user 
      password: user123
      database: sampledb
